name: Sync Selected Scoop Manifests

on:
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 04:00 UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run sync script
        run: python sync_manifests.py

      - name: Commit and push changes
        id: commit_step
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add bucket
          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "committed=false" >> $GITHUB_OUTPUT
          else
            git commit -m "Sync manifests (auto-update)"
            git push
            echo "committed=true" >> $GITHUB_OUTPUT
          fi

      - name: Send Pushover notification
        if: steps.commit_step.outputs.committed == 'true'
        run: |
          curl -s \
            --form-string "token=${{ secrets.PUSHOVER_APP_TOKEN }}" \
            --form-string "user=${{ secrets.PUSHOVER_USER_KEY }}" \
            --form-string "title=Scoop Auto Sync" \
            --form-string "message=✅ Scoop manifests were updated and committed." \
            https://api.pushover.net/1/messages.json